[project]
name = "codesnap.nvim"
version = "1.3.1"
description = "📸 Snapshot plugin that can make pretty code snapshots with real-time previews for Neovim"
author = "Mist"
email = "mist.zzh@gmail.com"
