name: Auto Generate Contributor List

on:
  push:
    branches:
      main

permissions:
  contents: write

jobs:
  generate-contributor-list:
    name: Auto generate contributor list
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: CONTRIBUTORS.svg
